version: "3"
services:
  gateway:
    container_name: gateway
    build:
      context: .
      args:
        - APP=gateway
    restart: always
    env_file:
      - apps/gateway/development.env
    ports:
      - '3000:3000'
  book:
    container_name: book
    build:
      context: .
      args:
        - APP=book
    restart: always
    env_file:
      - apps/book/development.env
  order:
    container_name: order
    build:
      context: .
      args:
        - APP=order
    restart: always
    env_file:
      - apps/order/development.env
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: >
      --requirepass redis
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=development
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
